### ISSUE TITLE
ubuntu 20.04 lts hangs (dmesg: `uncorrectable I/O failure`)

### ISSUE THREAD

**Issue by xsbymz** [saveriomiroddi/zfs-installer#104] opened 2020-04-28 14:30 UTC
[dmesg output.txt](https://github.com/saveriomiroddi/zfs-installer/files/4546304/dmesg.output.txt)
[disks.log](https://github.com/saveriomiroddi/zfs-installer/files/4546319/disks.log)
[install.log](https://github.com/saveriomiroddi/zfs-installer/files/4546320/install.log)
[os_information.log](https://github.com/saveriomiroddi/zfs-installer/files/4546321/os_information.log)
[updated_module_versions.log](https://github.com/saveriomiroddi/zfs-installer/files/4546322/updated_module_versions.log)

using ubuntu live 20.04 lts

its hanging at part 

```
###############################################################################
# remove_temp_partition_and_expand_rpool
###############################################################################
Linux ubuntu 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by xsbymz** [comment] 2020-04-28 15:32
at ubuntu 18.04 i just see this in dmesg 
Pool 'rpool' has encountered an uncorrectable I/O failure and has been suspended.

**Comment by saveriomiroddi** [comment] 2020-04-28 20:27
Hello! So, the information as it is points to a hardware problem (although of course, nothing can be really ruled out, for example, unexpected interactions with zdev), so I need to make it clear that there is a distinct possibilty that I won't be able to solve the problem.

Having said that, I've just released a new ZFS installer version that improves the logging for setups where a password is entered.

So if you retry the installation on 18.04, and send again the new logs (along with the dmesg output), I'll extract a minimal test case, and hope to reproduce the problem.

**Comment by saveriomiroddi** [comment] 2020-04-30 10:48
(Closed by accident)

**Comment by saveriomiroddi** [comment] 2020-05-12 15:45
Closing for inactivity.

**Comment by anthr76** [comment] 2020-05-17 00:48
I am also receiving this error. Doesn't seem hardware related though this server was previously linux_raid. It's a cloud hosted server with OVH. 

dmesg 
```
[ 2568.864814] WARNING: Pool 'rpool' has encountered an uncorrectable I/O failure and has been suspended.

[ 2780.384535] INFO: task txg_sync:50306 blocked for more than 120 seconds.
[ 2780.384540]       Tainted: P           O      5.4.0-26-generic #30-Ubuntu
[ 2780.384541] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```
```
###############################################################################
# remove_temp_partition_and_expand_rpool
###############################################################################

warning: device '/dev/disk/by-id/ata-HGST_HUS724040ALA640_PN1334PCKA81VS-part3' onlined, but remains in faulted state
use 'zpool replace' to replace devices that are no longer present
warning: device '/dev/disk/by-id/ata-HGST_HUS724040ALA640_PN1338P4HEEBHB-part3' onlined, but remains in faulted state
use 'zpool replace' to replace devices that are no longer present
```

Also mount point was not automatically selected for me in the installer. I manually specified `/`.

I'm going to try not updating the installer. It was throwing lots of errors.

Ubuntu 20.04

**Comment by saveriomiroddi** [comment] 2020-05-17 10:09
@anthr76 Hello! Thanks for the report. I'll ask you for feedback over the next days. Unfortunately, this is likely to not a bug in a strict sense, so what I can attempt to do, is to gather a minimal test case, and work on it - at that point, we'll have a better idea (I can't exclude it's a ZFS quirk). I will ask you for feedback over the next days.

**Comment by saveriomiroddi** [comment] 2020-05-17 10:10
@anthr76 let's actually cut the chase :smile: Can you post the logs for an installation that causes that error? I will then extract the test case, and ask you to try it in isolation.

**Comment by Bragorr** [comment] 2020-05-27 10:42
I am having the same problem.

[disks.log](https://github.com/saveriomiroddi/zfs-installer/files/4688195/disks.log)
[install.log](https://github.com/saveriomiroddi/zfs-installer/files/4688197/install.log)
[os_information.log](https://github.com/saveriomiroddi/zfs-installer/files/4688198/os_information.log)
[running_processes.log](https://github.com/saveriomiroddi/zfs-installer/files/4688199/running_processes.log)
[updated_module_versions.log](https://github.com/saveriomiroddi/zfs-installer/files/4688200/updated_module_versions.log)

**Comment by saveriomiroddi** [comment] 2020-05-27 11:11
> I am having the same problem.
> 
> [disks.log](https://github.com/saveriomiroddi/zfs-installer/files/4688195/disks.log)
> [install.log](https://github.com/saveriomiroddi/zfs-installer/files/4688197/install.log)
> [os_information.log](https://github.com/saveriomiroddi/zfs-installer/files/4688198/os_information.log)
> [running_processes.log](https://github.com/saveriomiroddi/zfs-installer/files/4688199/running_processes.log)
> [updated_module_versions.log](https://github.com/saveriomiroddi/zfs-installer/files/4688200/updated_module_versions.log)
> 
> Do you need anything else?

Thanks for the logs! I'll review over today, then we can follow up. What I'm going to do is to extract a minimal test case, and ask you to try it.

**Comment by Bragorr** [comment] 2020-05-27 11:19
Thanks a lot!

**Comment by Bragorr** [comment] 2020-05-27 11:22
All three disks report corrupted data:
`zpool status -v rpool
  pool: rpool
 state: SUSPENDED
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-HC
  scan: none requested
config:

        NAME                                         STATE     READ WRITE CKSUM
        rpool                                        UNAVAIL      0     0     0  insufficient replicas
          raidz2-0                                   UNAVAIL      0     0     0  insufficient replicas
            ata-WDC_WD82PURZ-85TEUY0_VDHVK11K-part3  FAULTED      0     0     0  corrupted data
            ata-WDC_WD82PURZ-85TEUY0_VDHW2GKK-part3  FAULTED      0     0     0  corrupted data
            ata-WDC_WD82PURZ-85TEUY0_VDHWN7YK-part3  FAULTED      0     0     0  corrupted data

errors: List of errors unavailable: pool I/O is currently suspended
`

**Comment by Bragorr** [comment] 2020-05-27 11:39
Maybe a
`zpool offline "$v_rpool_name" "$selected_disk-part3"`
would help here
`  for selected_disk in "${v_selected_disks[@]}"; do
    parted -s "$selected_disk" rm 4
    parted -s "$selected_disk" unit s resizepart 3 -- "$resize_reference"
    zpool online -e "$v_rpool_name" "$selected_disk-part3"
  done`

**Comment by saveriomiroddi** [comment] 2020-05-27 20:27
> Maybe a
> `zpool offline "$v_rpool_name" "$selected_disk-part3"`
> would help here
> ` for selected_disk in "${v_selected_disks[@]}"; do parted -s "$selected_disk" rm 4 parted -s "$selected_disk" unit s resizepart 3 -- "$resize_reference" zpool online -e "$v_rpool_name" "$selected_disk-part3" done`

The `online -e` here is used for expanding the pool. Any idea is good, although, I've done a bit of research, and there's not specification of requiring any condition in order to execute `online -e`. I'm checking the logs now.

**Comment by saveriomiroddi** [comment] 2020-05-27 20:57
> All three disks report corrupted data:
> `zpool status -v rpool
> pool: rpool
> state: SUSPENDED
> status: One or more devices are faulted in response to IO failures.
> action: Make sure the affected devices are connected, then run 'zpool clear'.
> see: http://zfsonlinux.org/msg/ZFS-8000-HC
> scan: none requested
> config:
> 
> ```
>     NAME                                         STATE     READ WRITE CKSUM
>     rpool                                        UNAVAIL      0     0     0  insufficient replicas
>       raidz2-0                                   UNAVAIL      0     0     0  insufficient replicas
>         ata-WDC_WD82PURZ-85TEUY0_VDHVK11K-part3  FAULTED      0     0     0  corrupted data
>         ata-WDC_WD82PURZ-85TEUY0_VDHW2GKK-part3  FAULTED      0     0     0  corrupted data
>         ata-WDC_WD82PURZ-85TEUY0_VDHWN7YK-part3  FAULTED      0     0     0  corrupted data
> ```
> 
> errors: List of errors unavailable: pool I/O is currently suspended`

@Bragorr can you try using `GET https://git.io/JfrHd | sudo bash`?

A potential cause is that after resizing the partitions, `/dev` is not in sync, causing corruption. That doesn't really explain the problem, as if ZFS expands, it implies that `/dev` is updated with the changes, but it's worth a try.

I'm not sure what the alternative would be. There are no explicit procedures around, and the people performing the same procedure, don't do anything between the partition and the pool size - however, the difference is that they're very likely doing this manually, which would explain the difference.

**Comment by Bragorr** [comment] 2020-05-28 07:46
I get "Gerät ist belegt" probably something like "device is busy" but at a much earlier point (see logs). That is strange...

[disks.log](https://github.com/saveriomiroddi/zfs-installer/files/4694038/disks.log)
[install.log](https://github.com/saveriomiroddi/zfs-installer/files/4694040/install.log)
[os_information.log](https://github.com/saveriomiroddi/zfs-installer/files/4694041/os_information.log)
[running_processes.log](https://github.com/saveriomiroddi/zfs-installer/files/4694042/running_processes.log)
[updated_module_versions.log](https://github.com/saveriomiroddi/zfs-installer/files/4694043/updated_module_versions.log)

**Comment by Bragorr** [comment] 2020-05-28 10:10
I exchanged an old, recycled SATA cable. Now I am back to the same error:
[disks.log](https://github.com/saveriomiroddi/zfs-installer/files/4694815/disks.log)
[install.log](https://github.com/saveriomiroddi/zfs-installer/files/4694816/install.log)
[os_information.log](https://github.com/saveriomiroddi/zfs-installer/files/4694817/os_information.log)
[running_processes.log](https://github.com/saveriomiroddi/zfs-installer/files/4694818/running_processes.log)
[updated_module_versions.log](https://github.com/saveriomiroddi/zfs-installer/files/4694819/updated_module_versions.log)

**Comment by saveriomiroddi** [comment] 2020-05-28 12:38
> I exchanged an old, recycled SATA cable. Now I am back to the same error:
> [disks.log](https://github.com/saveriomiroddi/zfs-installer/files/4694815/disks.log)
> [install.log](https://github.com/saveriomiroddi/zfs-installer/files/4694816/install.log)
> [os_information.log](https://github.com/saveriomiroddi/zfs-installer/files/4694817/os_information.log)
> [running_processes.log](https://github.com/saveriomiroddi/zfs-installer/files/4694818/running_processes.log)
> [updated_module_versions.log](https://github.com/saveriomiroddi/zfs-installer/files/4694819/updated_module_versions.log)

Hello! So! I've prepare a script with the minimal test case. To execute it:

```sh
# can inspect it after download
wget -O test_case.sh https://git.io/JfoCe
sudo bash test_case.sh
```

Please execute it an let me know how it goes. It will take less than a minute, and perform the same partition/filesystem operations that the installer does (it will destroy the disks content).

If the script fails, that's great, because I'll be able to forward the test case as is to the ZFS mailing list, where they'll shed some light.

If it doesn't fail, it's a problem. This test case does something that the main script doesn't do - it explicitly clears ZFS labels - however, this shouldn't make a difference, therefore, the Ubuntu installer would be connected in a way or another.  
I'll still send a request to the ZFS mailing list, but it will be more difficult to diagnose the problem.

**Comment by Bragorr** [comment] 2020-05-28 12:45
Hi,
I am sorry, I just completed my install using this instructions: https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2018.04%20Root%20on%20ZFS.html
It didn't work for me either at first, because I had to install some zfs stuff for it to work.
I will do another install in a couple of weeks. I will try your scipt then. If I hit the same problems, I will try your test case.
Please don't be angry with me, but I am trying since last week to get this machine running to replace a dying one. I really don't feel like delaying any further.
I am sorry.

**Comment by saveriomiroddi** [comment] 2020-05-28 12:48
> Hi,
> I am sorry, I just completed my install using this instructions: https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2018.04%20Root%20on%20ZFS.html
> It didn't work for me either at first, because I had to install some zfs stuff for it to work.
> I will do another install in a couple of weeks. I will try your scipt then. If I hit the same problems, I will try your test case.
> Please don't be angry with me, but I am trying since last week to get this machine running to replace a dying one. I really don't feel like delaying any further.
> I am sorry.

Sure, no problem :smile:

**Comment by saveriomiroddi** [comment] 2020-05-28 13:43
For reference, I've asked [on the ZFS mailing lists](https://zfsonlinux.topicbox.com/groups/zfs-discuss/T892b381ae5594506/can-a-partition-underlying-a-pool-be-safely-extended-while-the-pool-is-online).

**Comment by ydylla** [comment] 2020-12-11 17:20
Hi,
I had the same problem on Ubuntu Server 20.04.
The installer only works when I do **not** leave unallocated space at the end of the disks. Nobody has mentioned this so far so maybe it helps to narrow it down.
I also tried your proposed "udevadm settle" fix before each resize but it did not help either.

**Comment by saveriomiroddi** [comment] 2020-12-16 11:22
@ydylla thanks for the feedback!

If you can reproduce this problem on every attempt, *and* you have a week of patience, a solution I can try is to export the ZFS filesystems before resizing, then resize, then reimport and expand them.

There's no guarantee this can work, but if you can test (I can't; this issue happens only on certain setups) it, I can rule out this workaround or confirm that ti works.

If you can't, then the alternative is either to put the workaround without verifying its effectiveness, or to just disable the space recovery functionality.

**Comment by ydylla** [comment] 2020-12-16 17:25
@saveriomiroddi
Yes I could reproduce it on multiple attempts. I also found a workaround which you could maybe add to the installer.
Sorry I did not mention it earlier. 

When the tail space at the end is bigger than the install partition (12GB) one could simply substract the 12GB from the desired tail size. This way the install partition temporary lives in the tail space and the zfs partition is created with the correct size. After the installation is finished the install partition can just be delete and become part of the unallocated tail space again. Thus the zfs resize is not needed at all.

I think despite the minimum size requirement for the tail space this would work for many people. For installations without free tail space the zfs resize would still be required. But like I said the zfs resize worked fine on my system without free tail space configured.

Sadly I can not test your export workaround anymore since the system is already in use again.

**Comment by saveriomiroddi** [comment] 2020-12-17 20:56
I've thought to use the same workaround, but I prefer to have a general, stable solution rather than a workaround. Unfortunately, I can't reproduce, and typically, when I try to to work with people affected by the problem, they worked the problem around in some other way :grimacing: :joy: 

I'm trying another approach to the problem - exporting the pools before resizing the partition, the reimporting them and following up. Possibly, ZFS doesn't like it when a partition is resized while it's running (but nothing is obvious about this, since on the official mailing list, nobody replied).

**Comment by saveriomiroddi** [comment] 2020-12-17 20:56
I'm going to release the workaround, and close this issue.

If anybody will experience the problem again, feel free to reopen the issue.

**Closed** 2020-12-17 21:16 UTC
Labels: high priority
