### ISSUE TITLE
Enable users to choose number of iterations and other key derivation settings, when available

### ISSUE THREAD

**Issue by vstoykovbg** [saveriomiroddi/zfs-installer#139] opened 2020-08-21 14:06 UTC
I hope the modern KDFs will be implemented soon.

For now, the only KDF setting is pbkdf2iters (the number of iterations).

https://github.com/openzfs/zfs/issues/10764

**Comment by saveriomiroddi** [comment] 2020-08-24 07:50
> I hope the modern KDFs will be implemented soon.
> 
> For now, the only KDF setting is pbkdf2iters (the number of iterations).
> 
> [openzfs/zfs#10764](https://github.com/openzfs/zfs/issues/10764)

Hello, the issue is unclear - what is exactly requested?

**Comment by saveriomiroddi** [comment] 2020-08-27 11:06
Closing this, because I can't implement something that it's not available :smile: Additionally, I think that if this will be implemented upstream, it will be configurable on pool/volume creation.

**Closed by saveriomiroddi** 2020-08-27 11:06 UTC
Labels: requires feedback
